### ISSUE TITLE
I clone the git but it did not build or run

### ISSUE THREAD

**Issue by theaaksa** [firebase/firebaseui-web#1027]
C:\Users\moham\Downloads\web-project>git clone https://github.com/firebase/firebaseui-web.git
Cloning into 'firebaseui-web'...
remote: Enumerating objects: 4883, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 4883 (delta 10), reused 2 (delta 2), pack-reused 4865Receiving objects: 100% (4883/4883), 5.89 MiB | 5.88 Receiving objects: 100% (4883/4883), 9.31 MiB | 7.18 MiB/s, done.

Resolving deltas: 100% (3376/3376), done.

C:\Users\moham\Downloads\web-project>cd firebaseui-web

C:\Users\moham\Downloads\web-project\firebaseui-web>npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated tweetsodium@0.0.5: tweetsodium is deprecated and unmaintained. Please consider using libsodium.js, maintained by the same author as libsodium: https://github.com/jedisct1/libsodium.js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated protractor@7.0.0: We have news to share - Protractor is deprecated and will reach end-of-life by Summer 2023. To learn more and find out about other options please refer to this post on the Angular blog. Thank you for using and contributing to Protractor. https://goo.gle/state-of-e2e-in-angular
npm WARN deprecated closure-builder@2.3.8: Package no longer updated and supported. Use at your own risk.

> firebaseui@6.0.2 prepublish
> npm run test && cp -r dist demo/public

> firebaseui@6.0.2 test
> npm run build && npm run generate-test-files && ./buildtools/run_tests.sh

> firebaseui@6.0.2 build
> gulp

[07:29:58] Using gulpfile ~\Downloads\web-project\firebaseui-web\gulpfile.js
[07:29:58] Starting 'default'...
[07:29:58] Starting 'build-externs'...
[07:29:58] Finished 'build-externs' after 39 ms
[07:29:58] Starting 'build-ts'...
[07:29:58] Finished 'build-ts' after 11 ms
[07:29:58] Starting 'build-js'...
[07:29:58] Starting 'build-js-en'...
[07:29:58] Starting 'build-firebaseui-js-en'...
[07:29:58] Starting 'build-externs'...
[07:29:58] Starting 'build-ts'...
[07:29:58] Starting 'build-soy'...
[14%] soy_files Compiling 3 soy files to out (0.1 sec)[07:29:58] Finished 'build-ts' after 144 ms
[07:29:58] Finished 'build-externs' after 148 ms
[Closure Templates Error] Exception in thread "main" com.google.inject.internal.util.$ComputationException: java.lang.ExceptionInInitializerError
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
        at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)        at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:507)
        at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:159)
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at com.google.template.soy.MainClassUtils.createInjector(MainClassUtils.java:221)
        at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:265)
        at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)
Caused by: java.lang.ExceptionInInitializerError
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:207)
        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:53)
        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:153)
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:89)
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
        at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
        ... 15 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @b1a58a3
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:201)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:195)
        at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
        ... 29 more

[07:29:59] The following tasks did not complete: default, build-js, build-js-en, <parallel>, build-firebaseui-js-en, <parallel>, build-soy
[07:29:59] Did you forget to signal async completion?
npm ERR! code 1
npm ERR! path C:\Users\moham\Downloads\web-project\firebaseui-web
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run test && cp -r dist demo/public

npm ERR! A complete log of this run can be found in: C:\Users\moham\AppData\Local\npm-cache\_logs\2023-06-07T04_28_19_474Z-debug-0.log

**Comment by theaaksa** [comment]
C:\Users\moham\Downloads\web-project\firebaseui-web>node -v
v18.16.0

C:\Users\moham\Downloads\web-project\firebaseui-web>firebase tools --version
12.3.1

Edition	Windows 11 Home
Version	22H2
Installed on	‎10/‎24/‎2022
OS build	22621.1778
Experience	Windows Feature Experience Pack 1000.22642.1000.0

**Comment by rachelmyers** [comment]
This is meant to be included in an app rather than run on its own. If you're trying to build it to do local development or do localization, we offer build instructions in the [README] https://github.com/firebase/firebaseui-web#developer-setup. If that still doesn't work, please reopen and let us know what step failed.
