### ISSUE TITLE
Travis integration tests broken

### ISSUE THREAD

**Issue by bojeil-google** [firebase/firebaseui-web#124]
Travis integration tests are currently broken.
https://travis-ci.org/firebase/firebaseui-web/builds/218675525

> closure-builder@2.0.25 configure /home/travis/build/firebase/firebaseui-web/node_modules/closure-builder
> node configure.js
/home/travis/build/firebase/firebaseui-web/node_modules/closure-builder/tools/file.js:88
  var fileEvent = (error) => {
                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/firebase/firebaseui-web/node_modules/closure-builder/configure.js:22:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by bojeil-google** [comment]
Issue appears to be a temporary hiccup. Tests are passing again. Closing this issue.
