### ISSUE TITLE
Throw exception after logout and then login again

### ISSUE THREAD

**Issue by miketran13** [firebase/firebaseui-web#13]
I used firebaseui for login then I called firebase.auth().signOut(). After that I come back to the login page and when starting the firebase ui login, it thrown an exception that is "User not logged in"

browser_adapter.js:77 Error: User not logged in.
    at Error (native)
    at Dj (https://www.gstatic.com/firebasejs/ui/0.4.0/firebase-ui-auth.js:235:156)
    at Wj (https://www.gstatic.com/firebasejs/ui/0.4.0/firebase-ui-auth.js:245:608)
    at Yj (https://www.gstatic.com/firebasejs/ui/0.4.0/firebase-ui-auth.js:245:489)
    at https://www.gstatic.com/firebasejs/ui/0.4.0/firebase-ui-auth.js:247:96
    at e.Ub (http://localhost:8100/lib/firebase.js:78:495)
    at Qd (http://localhost:8100/lib/firebase.js:82:220)
    at Md (http://localhost:8100/lib/firebase.js:82:100)
    at C.Rg (http://localhost:8100/lib/firebase.js:81:406)
    at td (http://localhost:8100/lib/firebase.js:74:484)BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:60(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:112onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259ZoneTask.invoke @ zone.js:423
Subscriber.js:227 Uncaught Error: User not logged in.

**Comment by bojeil-google** [comment]
Can you please provide a code snippet to help us debug. It appears like you are signing out in the middle of a sign in attempt but this is mere speculation without any code to back it up.

**Comment by miketran13** [comment]
Hi,
I have checked the current user state that is signed in or not. It is only be able to sign out if the current user have the value. It happened when I signed in with Google and it was successfully with all my information.

This is the code snippet:

Here is the code that init the login ui:

 ```
public initLoginUI()
    {
      var auth = firebase.auth();     
      var ui = new firebaseui.auth.AuthUI(auth);
      
        // FirebaseUI config.
      var uiConfig = {
        // Query parameter name for mode.
        'queryParameterForWidgetMode': 'mode',
        'signInSuccessUrl': Constants.HOME_PAGE_URL,
        'queryParameterForSignInSuccessUrl': 'signInSuccessUrl',
        // Query parameter name for sign in success url.
        'signInOptions': [
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.FacebookAuthProvider.PROVIDER_ID,
          firebase.auth.TwitterAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID
        ],
        // Terms of service url.
        'tosUrl': Constants.TERM_OF_SERVICE_URL,
        'callbacks': {
          'signInSuccess': (currentUser, credential, redirectUrl) => {
            this.logger.log("Sign in success!");
            return  false;
          }
        }
      };
      // The start method will wait until the DOM is loaded.
      ui.start(this.LOGIN_UI_ELEMENT_ID, uiConfig);        
    }
```
Here is the code for logout(this is only be able to trigger after login success):

```
firebase.auth().signOut().then(() => {
     
      this.isUserLoggedIn = false;
     
    }, (error) => {
      //todo
    });

```

**Comment by TMSCH** [comment]
Hi Mike,
Thanks for the snippets! This is actually a known issue. FirebaseUI currently does not work well in single page application. We are working on a solution to prevent this issue. In the meanwhile, you can redirect to the widget or open it in a new window.

**Comment by miketran13** [comment]
That's great! I'm looking forward to hearing the new version.

**Comment by TMSCH** [comment]
Hi @miketran13, we added a new method, reset(), that allows to dispose of the widget before re-rendering it again. Please look at the release notes: https://github.com/firebase/firebaseui-web#050 as well as the updated demo app in the repo. It showcases an app using FirebaseUI in a Single Page Application context.

**Comment by miketran13** [comment]
That's great! Thanks. I need it now.
