### ISSUE TITLE
npm run demo breaks every time

### ISSUE THREAD

**Issue by heyjohnmurray** [firebase/firebaseui-web#138]
I'm trying to launch the demo locally, but every time I do `npm run demo` I get this error:

```
[12:43:28] Finished 'build-css' after 562 ms

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: Command failed: java -jar -XX:-TieredCompilation node_modules/google-closure-compiler/compiler.jar --flagfile="/var/folders/85/g4kmrn5518xf874b0lvp75cw0000gp/T/6f80dc7f-d5a2-4604-8144-3a6ff85e03ba" --closure_entry_point=firebaseui.auth.exports --compilation_level=ADVANCED_OPTIMIZATIONS --externs=node_modules/firebase/externs/firebase-app-externs.js --externs=node_modules/firebase/externs/firebase-auth-externs.js --externs=node_modules/firebase/externs/firebase-client-auth-externs.js --only_closure_dependencies=true --output_wrapper=(function() { %output% })(); --js_output_file="firebaseui.js"
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

my node, npm, java and python versions are up-to-date. 

any idea what's going on and why I run into a java error trying to compile

**Comment by TMSCH** [comment]
What version of Java are you using? To find out run `java -version` in a terminal.

**Comment by heyjohnmurray** [comment]
@TMSCH with that terminal command i get back:

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)


when i click through system preferences on my mac i get:

java 8 update 131

**Comment by TMSCH** [comment]
@heyjohnmurray it seems that the version you get in the terminal is different than the system's. Have you manually installed Java? Through Homebrew or similar package manager?
I'd recommend upgrading the Java version that is actually used in your terminal to 8, and try again.

**Comment by heyjohnmurray** [comment]
I did install manually but through the java site and not through terminal. I installed it through homebrew, and that seems to have resolved the problem thanks so much. Now onto the other errors it's throwing 👍

**Comment by TMSCH** [comment]
Great! Glad we solved this problem :)

**Comment by EmberJSParis** [comment]
I have the same problem as above, My Java config is -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11
)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11,
 mixed mode) ...................I am on Mac and I installed Java in usr/local/bin/java through the command brew cask install java .......................when I ran "npm run demo --project IDofproject" I get this error "Error: No project active. Run with --project <projec
tId> or define an alias by
running firebase use --add" The initial objective it was to ran https://github.com/firebase/firebaseui-web/tree/master/demo but the error persist
