### ISSUE TITLE
[request] Easier way of switching languages

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebaseui-web#242]
There is currently no easy way to add a couple of CDNs for several languages of the UI, then load the correct UI based on a parameter.

The page is in a certain language, how to make sure the correct UI gets used even after the user chooses a different language?

**Comment by bojeil-google** [comment]
Each internationalized version is a separate build. Including all the versions in one file is not feasible.
Typically if a user switches languages, you would redirect to another page (eg. https://www.example.com/auth?lang=ja") and load the UI version with the selected language.

**Comment by bojeil-google** [comment]
Technically, you could still do this with one HTML file, but you would need to reload the page. I haven't tested dynamically loading the localized binaries and overwriting the previous one. That could be an option. I will need to test that. 

Including all localized versions in one file is not feasible.

By the way we provide the ability to build the localized binary with npm. You could use that to build your own multi-language supporting version. Personally I don't recommend that approach and I prefer either reloading the page or dynamically loading the localized binary.

**Comment by mesqueeb** [comment]
Dear @bojeil-google 
I tried to build it from the dev version following these steps:
1. `git clone https://github.com/firebase/firebaseui-web.git`
2. `cd firebaseui-web`
3. `npm install`
4. `npm run build`

However, after building it, adding it as a static asset (making webpack copying the file as is), and also disabling babel on the file, I still get an error like this:

<img width="567" alt="2017-11-16 19 30 35" src="https://user-images.githubusercontent.com/3253920/32886642-a3175f64-cb04-11e7-9b99-e22efec37a0b.png">

I'm having trouble finding the bug. : S
Any ideas for me?

**Comment by bojeil-google** [comment]
As I explained earlier, multiple translations in one file is not recommended as it will multiply the size of the file by the number of languages you want to support and it will raise other issues. I described 2 approaches and none of them include multiple languages in one file. 
You can either reload the page with the new language, or we can help support client side dynamic loading of the language on selection. I still plan to experiment with that.

**Comment by mesqueeb** [comment]
@bojeil-google Do you have any advice for me how to load a different language in a Single Page Application?
Since I can only have 1 HTML file, I don't think the "refresh the page" method will work...

**Comment by nicolasgarnier** [comment]
I would use lazy-loading of the library. Your app will be too big and it is not good for performance to include all languages in the same bundle.

So you could still use a URL parameter or a has fragment, for instance let say you load

https://www.example.com/auth?lang=en

your code can be:

```js
const locale = 'en' // Read the locale from the URL parameter here!

const firebaseUILoader;
if (locale === 'en') {
  firebaseUILoader = import('../statics/firebaseui__en.js')
} else if ( (locale === 'ja') {
  firebaseUILoader = import('../statics/firebaseui__ja.js')
}

firebaseUILoader.then(firebaseui => {
  // You can use FirebaseUI here.
});
```

This is using Webpack's [dynamic import](https://webpack.js.org/guides/code-splitting/#dynamic-imports) feature. The different localised versions of Firebase will be generated in different chunks that will be loaded on the fly when requested.

As you can see above the library is loaded asynchroneously so you'll get firebaseui in a Promise. it gets nice though if you use async/await:


```js
const locale = 'en' // Read the locale from the URL parameter here!

async function loadFirebaseUI() {
  const firebaseui;
  if (locale === 'en') {
    firebaseui = await import('../statics/firebaseui__en.js')
  } else if ( (locale === 'ja') {
    firebaseui = await import('../statics/firebaseui__ja.js')
  }

  // You can use Firebase UI here.
}
```

btw @bojeil-google, it would be cool to provide all the localised JS files in the NPM distrib so taht developers could do that easily.

**Comment by pdela** [comment]
I'm building a PWA, using firebase and angularfire as npm modules.
I want my user to be able to switch language on the fly (without reloading html possibly).

I tried to lazy load the correct firebaseui js file from CDN, but then since the firebase module is loaded from npm, firebaseui throws an error (firebase is not defined).

So I'm trying to build localized npm packages, but I'm having problems.

Followed:

1. git clone https://github.com/firebase/firebaseui-web.git
2. cd firebaseui-web
3. npm install **(fails!)**
So clearly fails also:
4. npm build build-npm-it

I'm using Windows 10. Installed gulp and python (not sure I installed the version required), which seemed needed into the system. No luck.

I'm in a loop! Please help!

**Here is the log:**
npm install

> node-sass@3.13.1 install C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> grpc@1.16.1 install C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node" is installed via remote

> closure-builder@2.3.2 install C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\closure-builder
> npm run configure


> closure-builder@2.3.2 configure C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\closure-builder
> node configure.js

Configuring Closure Builder 2.3.2 ...

Downloading Google Closure Templates Compiler ...
Downloading 4 files for Google Closure Stylesheets ...
Optimizing Google Closure Library ...
Optimizing Google Closure Templates ...
Perform basic Java checks ...
Found global Java ... 1.8.0_161
Downloading LICENSE [====================] 100% 0.0s
Downloading README.md [====================] 100% 0.0s
Downloading closure-templates-for-javascript-latest.zip [====================] 100% 0.0s
Extracting Google Closure Templates Compiler please wait ...
Downloading closure-stylesheets-library.jar [====================] 100% 0.0s
Downloading closure-stylesheets.jar [====================] 100% 0.0s

> node-sass@3.13.1 postinstall C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\paolo\\Dropbox\\_100-Bambanada\\WebProjects\\firebaseui-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\paolo\AppData\Local\Programs\Python\Python37-32\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\paolo\AppData\Local\Programs\Python\Python37-32\python.exe C:\Users\paolo\AppData\Local\Programs\Python\Python37-32\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\paolo\AppData\Local\Programs\Python\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\paolo\\Dropbox\\_100-Bambanada\\WebProjects\\firebaseui-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\node_modules\node-sass
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@20181210.0.0 (node_modules\google-closure-compiler\node_modules\google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20181210.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-linux@20181210.0.0 (node_modules\google-closure-compiler\node_modules\google-closure-compiler-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-linux@20181210.0.0: wanted {"os":"linux","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@20180805.0.0 (node_modules\google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20180805.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-linux@20180805.0.0 (node_modules\google-closure-compiler-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-linux@20180805.0.0: wanted {"os":"linux","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paolo\AppData\Roaming\npm-cache\_logs\2019-03-01T22_58_59_095Z-debug.log


**and the log for** 
npm build build-npm-it

npm ERR! path C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\build-npm-it\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\paolo\Dropbox\_100-Bambanada\WebProjects\firebaseui-web\build-npm-it\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paolo\AppData\Roaming\npm-cache\_logs\2019-03-01T22_59_12_745Z-debug.log

**Comment by yevheniidehtiar** [comment]
I use vue + webpack. Localized modules are loaded async / await import successfully,
but when creating a widget instance  `new firebaseui.auth.AuthUI (appId) `- an error crashes: 
`Uncaught (in promise) ReferenceError: firebase is not defined
    at new Dn (firebase-ui-auth__uk.js?c470:formatted:1)
    at eval (Auth.vue?1e10:41)`
on row `var x = new firebase.auth.RecaptchaVerifier(um ? n.jg() : n.H(),e,An(a).app);`

On the top of `<script>` block of page i have `import * as firebase from 'firebase';` and I tried it like `import firebase from 'firebase'`;

**Comment by wti806** [comment]
@yevheniidehtiar Does this error only happen with localized version? And how did you load the module?

**Comment by tohagan** [comment]
> Each internationalized version is a separate build. Including all the versions in one file is not feasible.

Oh dear.  Looks like you've used the wrong implementation architecture to support i18n for SPA web apps!

> Typically if a user switches languages, you would redirect to another page (eg. https://www.example.com/auth?lang=ja") and load the UI version with the selected language."

Except that we're all coding SPA web apps today so we don't reload pages from the server just one stati page index.html and our client side "pages" are not server side rendered (remember: Firebase hosting is for **static** pages!) So making a Firebase UI build per language is inherently broken. 

More commonly we wish to provide a feature in our SPA app to allow the user to change their language, dynamically. We expect that will only need to lazy load a small JSON file to import the language changes and we inject **a single** CSS that can auto adapt to RTL when need.

Now Firebase UI will **just work** by inspecting `window.navigator.languages` and to on of the supported language JSON files a default language (like "en") if no matching locale is found.

## Hacky workarounds ... 

Okay so I can kinda patch this up by inspecting `window.navigator.languages`, then creating a mapping function to convert real browser locales to the different ones provided by Firebase UI and do a dynamic load from the CDN of the language specific build. That might for for non-RTL languages but it's till broken for RTL languages since I have no way to dynamically load the right CSS file. 

Yuck! Please fix.

**Comment by bonatoc** [comment]
> assists with this restriction

@tohagan As I'm building a SPA (possibly a PWA, possibly a PWA+SSR) with [Quasar](https://quasar.dev/), I'm really interested in your workaround. 

FirebaseUI Team: I find it odd, to say the least, that Google promotes PWA all year round, but then you couldn't come up with some real-time detection/switch for the language used.
This speaks volumes on how some developers (or product managers) think english is the sole spoken language across the world (you'll pardon the rant, it is well deserved).
i18n hot switching should be thought of right from the start and from the ground up, 
whatever the web software project.

Could you please share your approach? 
Many thanks.

**Comment by bonatoc** [comment]
> I use vue + webpack. Localized modules are loaded async / await import successfully,
> but when creating a widget instance `new firebaseui.auth.AuthUI (appId) `- an error crashes:
> `Uncaught (in promise) ReferenceError: firebase is not defined at new Dn (firebase-ui-auth__uk.js?c470:formatted:1) at eval (Auth.vue?1e10:41)`
> on row `var x = new firebase.auth.RecaptchaVerifier(um ? n.jg() : n.H(),e,An(a).app);`
> 
> On the top of `<script>` block of page i have `import * as firebase from 'firebase';` and I tried it like `import firebase from 'firebase';` ...but without positive result

Same problem with JS binaries, using Quasar (Webpack).

default import works:
`import * as firebaseui from 'firebaseui'`

This doesn't:
`import * as firebaseui from 'firebaseui/dist/firebaseui__it'`

nor:
`import firebaseui from 'firebaseui/dist/firebaseui__it'`


Console error:
`TypeError: Cannot read property 'AuthUI' of undefined`

**Comment by dackers86** [comment]
Thank you for taking the time to submit this issue.

A new release is planned shortly, which should resolve this request. 

In the meantime, we will close this issue, if this is not resolved in the new version - please feel free to create a new issue.
