### ISSUE TITLE
[Closure Templates Error] Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

### ISSUE THREAD

**Issue by ferleal** [firebase/firebaseui-web#378]
I am trying to build localized version
git clone https://github.com/firebase/firebaseui-web.git
cd firebaseui-web
npm install
but I having and error on the install

ubuntu 16.04
node: 8.10.0
npm : 5.6.0
```batch
[14%] soy_files Compiling 3 soy files to out (0.1 sec)[Closure Templates Error] Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

1) null returned by binding at com.google.template.soy.SoyFileSet$SoyFileSetFactory.create()
 but parameter 9 of com.google.template.soy.SoyFileSet.<init>() is not @Nullable
  while locating com.google.template.soy.shared.SoyAstCache annotated with @com.google.inject.assistedinject.Assisted(value=)
    for parameter 9 at com.google.template.soy.SoyFileSet.<init>(SoyFileSet.java:610)
  while locating com.google.template.soy.SoyFileSet annotated with interface com.google.inject.assistedinject.Assisted

2) null returned by binding at com.google.template.soy.SoyFileSet$SoyFileSetFactory.create()
 but parameter 10 of com.google.template.soy.SoyFileSet.<init>() is not @Nullable
  while locating com.google.template.soy.types.SoyTypeRegistry annotated with @com.google.inject.assistedinject.Assisted(value=localTypeRegistry)
    for parameter 10 at com.google.template.soy.SoyFileSet.<init>(SoyFileSet.java:610)
  while locating com.google.template.soy.SoyFileSet annotated with interface com.google.inject.assistedinject.Assisted

2 errors
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:632)
        at com.google.template.soy.$Proxy22.create(Unknown Source)
        at com.google.template.soy.SoyFileSet$Builder.build(SoyFileSet.java:202)
        at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:286)
        at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)
```

**Comment by bojeil-google** [comment]
I am unable to replicate this. Can you provide the `google-closure-compiler` and `google-closure-library` versions you are using?

**Comment by ferleal** [comment]
Hello here is my package.json
```json
  "devDependencies": {
    "closure-builder": "^2.2.34",
    "firebase-tools": "^3.0.8",
    "fs-extra": "^3.0.1",
    "google-closure-compiler": "^20171112.0.0",
    "google-closure-library": "^20171112.0.0",
    "google-closure-templates": "^20150410.0.0",
    "gulp": "^3.9.1",
    "gulp-clean-css": "^2.0.12",
    "gulp-closure-compiler": "^0.4.0",
    "gulp-concat-css": "^2.3.0",
    "gulp-connect": "^5.0.0",
    "gulp-css-flip": "^0.4.0",
    "gulp-sass": "^2.3.2",
    "gulp-util": "^3.0.7",
    "material-design-lite": "^1.2.0",
    "phantomjs-prebuilt": "^2.1.13",
    "protractor": "^4.0.9",
    "streamqueue": "^1.1.1"
  },
  "dependencies": {
    "dialog-polyfill": "^0.4.7",
    "firebase": "^4.8.0"
  }

```

**Comment by nicolasgarnier** [comment]
@ferleal are you still experiencing the issue? (just checking because this has been stale for some month). Let us know if you still need assistance.
