### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by tomoyuki28jp** [firebase/firebaseui-web#598]
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.5
  * Browser version: chrome 74.0.3729.169 (unrelated)
  * Firebase UI version: firebaseui@4.0.0
  * Firebase SDK version: ?

#### Steps to reproduce:

`npm install`

```
[21:48:32] Using gulpfile /private/tmp/firebaseui-web/gulpfile.js
[21:48:32] Starting 'default'...
[21:48:32] Starting 'build-externs'...
[21:48:32] Finished 'build-externs' after 27 ms
[21:48:32] Starting 'build-ts'...
[21:48:32] Finished 'build-ts' after 5.52 ms
[21:48:32] Starting 'build-js'...
[21:48:32] Starting 'build-js-en'...
[21:48:32] Starting 'build-firebaseui-js-en'...
[21:48:32] Starting 'build-externs'...
[21:48:32] Starting 'build-ts'...
[21:48:32] Starting 'build-soy'...
[21:48:33] Finished 'build-externs' after 101 ms
[21:48:33] Finished 'build-ts' after 101 ms
[14%] soy_files Compiling 3 soy files to out (0.1 sec)[Closure Templates Error] Picked up JAVA_TOOL_OPTIONS: -Duser.language=en

[21:48:33] The following tasks did not complete: default, build-js, build-js-en, <parallel>, build-firebaseui-js-en, <parallel>, build-soy
[21:48:33] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebaseui@4.0.0 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebaseui@4.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomo/.npm/_logs/2019-06-17T12_48_33_819Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebaseui@4.0.0 test: `npm run build && npm run generate-test-files && ./buildtools/run_tests.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebaseui@4.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomo/.npm/_logs/2019-06-17T12_48_33_839Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebaseui@4.0.0 prepublish: `npm run test && cp -r dist demo/public`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebaseui@4.0.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomo/.npm/_logs/2019-06-17T12_48_33_897Z-debug.log
```

### /Users/tomo/.npm/_logs/2019-06-17T12_48_33_897Z-debug.log
```
31162 info lifecycle firebaseui@4.0.0~prepublish: firebaseui@4.0.0
31163 verbose lifecycle firebaseui@4.0.0~prepublish: unsafe-perm in lifecycle true
31164 verbose lifecycle firebaseui@4.0.0~prepublish: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/private/tmp/firebaseui-web/node_modules/.bin:/Users/tomo/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tomo/.embulk/bin:/Users/tomo/src/flutter/bin:/Users/tomo/Library/Android/sdk/tools:/Users/tomo/Library/Android/sdk/tools/bin:/Users/tomo/Library/Android/sdk/platform-tools:/Users/tomo/.nodebrew/current/bin
31165 verbose lifecycle firebaseui@4.0.0~prepublish: CWD: /private/tmp/firebaseui-web
31166 silly lifecycle firebaseui@4.0.0~prepublish: Args: [ '-c', 'npm run test && cp -r dist demo/public' ]
31167 silly lifecycle firebaseui@4.0.0~prepublish: Returned: code: 1  signal: null
31168 info lifecycle firebaseui@4.0.0~prepublish: Failed to exec prepublish script
31169 verbose stack Error: firebaseui@4.0.0 prepublish: `npm run test && cp -r dist demo/public`
31169 verbose stack Exit status 1
31169 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
31169 verbose stack     at EventEmitter.emit (events.js:182:13)
31169 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
31169 verbose stack     at ChildProcess.emit (events.js:182:13)
31169 verbose stack     at maybeClose (internal/child_process.js:962:16)
31169 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
31170 verbose pkgid firebaseui@4.0.0
31171 verbose cwd /private/tmp/firebaseui-web
31172 verbose Darwin 18.6.0
31173 verbose argv "/usr/local/Cellar/node/11.0.0/bin/node" "/usr/local/bin/npm" "install"
31174 verbose node v11.0.0
31175 verbose npm  v6.8.0
31176 error code ELIFECYCLE

```

**Comment by wti806** [comment]
@tomoyuki28jp I tried myself and it works for me. From the log you provided, it seems the build-js gulp task failed. We use [closure compiler](https://github.com/google/closure-builder#requirements) to build the js files, which depends on JRE. From the log, I see: [Closure Templates Error] Picked up JAVA_TOOL_OPTIONS: -Duser.language=en. I think probably it's related to your JRE set up.

**Comment by tomoyuki28jp** [comment]
@wti806 Removing `export JAVA_TOOL_OPTIONS=-Duser.language=en` from my .zhsnev solves my issue. Thanks a lot for your help!
