### ISSUE TITLE
npm run demo fails under ubuntu 19.04

### ISSUE THREAD

**Issue by Quantmatic** [firebase/firebaseui-web#652]
git clone https://github.com/firebase/firebaseui-web.git
cd firebaseui-web
npm install
firebase init
copy config.js to ../demo/public
npm run demo

`Error: No project active. Run with --project <projectId> or define an alias by
running firebase use --add
`
 firebase use --add doesn't resolve the issue
Log:

`0 info it worked if it ends with ok
1 verbose cli [ '/home/alpha/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/home/alpha/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo' ]
2 info using npm@6.12.0
3 info using node@v10.16.3
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle native-mcbunny@4.3.0~predemo: native-mcbunny@4.3.0
6 info lifecycle native-mcbunny@4.3.0~demo: native-mcbunny@4.3.0
7 verbose lifecycle native-mcbunny@4.3.0~demo: unsafe-perm in lifecycle true
8 verbose lifecycle native-mcbunny@4.3.0~demo: PATH: /home/alpha/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/alpha/Firebase/firebaseui-web/node_modules/.bin:/home/alpha/.nvm/versions/node/v10.16.3/bin:/home/alpha/miniconda3/bin:/home/alpha/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle native-mcbunny@4.3.0~demo: CWD: /home/alpha/Firebase/firebaseui-web
10 silly lifecycle native-mcbunny@4.3.0~demo: Args: [ '-c', 'npm run build && ./buildtools/run_demo.sh' ]
11 silly lifecycle native-mcbunny@4.3.0~demo: Returned: code: 1  signal: null
12 info lifecycle native-mcbunny@4.3.0~demo: Failed to exec demo script
13 verbose stack Error: native-mcbunny@4.3.0 demo: `npm run build && ./buildtools/run_demo.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/alpha/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/alpha/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid native-mcbunny@4.3.0
15 verbose cwd /home/alpha/Firebase/firebaseui-web
16 verbose Linux 5.0.0-36-generic
17 verbose argv "/home/alpha/.nvm/versions/node/v10.16.3/bin/node" "/home/alpha/.nvm/versions/node/v10.16.3/bin/npm" "run" "demo"
18 verbose node v10.16.3
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error native-mcbunny@4.3.0 demo: `npm run build && ./buildtools/run_demo.sh`
22 error Exit status 1
23 error Failed at the native-mcbunny@4.3.0 demo script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by wti806** [comment]
You need to run the command `firebase use --add` before running the demo to select a firebase project to use.

**Comment by Quantmatic** [comment]
Tried about everything, can't get it to work

If you do firebase init in the demo directory, it actually comes up on localhost:5000

But not the entire thing, just the header is visible, and there are multiple errors in the console

So the instructions are flawed....

firebaseui-web-react works out of the box

**Comment by wti806** [comment]
It works for me and the instruction hasn't been changed for a long time. Did you `cd` to `demo` folder before running `firebase use --add`? If still not working, please try `firebase logout` and `firebase login` again and then run `firebase use --add`.

**Comment by Quantmatic** [comment]
Can you post your CMD flow

**Comment by wti806** [comment]
git clone https://github.com/firebase/firebaseui-web.git
cd firebaseui-web
npm install
cd demo
firebase use --add // If something goes wrong here, run firebase logout and login again
cp public/sample-config.js public/config.js
npm run demo

**Comment by dackers86** [comment]
Thank you for taking the time to submit this issue.

A new release is planned shortly, which should resolve this request. 

In the meantime, we will close this issue, if this is not resolved in the new version - please feel free to create a new issue.
