### ISSUE TITLE
"." is not recognized - Windows 10

### ISSUE THREAD

**Issue by MartinVedani** [firebase/firebaseui-web#704]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: n/a
  * Firebase UI version: 4.5.0
  * Firebase SDK version: _____

### [REQUIRED] Describe the problem
**************************
SCREEN MESSAGE
*************************

> firebaseui@4.5.0 generate-test-files C:\Users\marti\Desktop\firebaseui-web
> ./buildtools/generate_test_files.sh

"." is not recognized as an internal or external command, program, or file by executable batch.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebaseui@4.5.0 generate-test-files: `./buildtools/generate_test_files.sh`
npm ERR! Exit status 1

**************************************
ENTIRE debug log
*************************************
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle firebaseui@4.5.0~pretest: firebaseui@4.5.0
6 info lifecycle firebaseui@4.5.0~test: firebaseui@4.5.0
7 verbose lifecycle firebaseui@4.5.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle firebaseui@4.5.0~test: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\marti\Desktop\firebaseui-web\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\marti\Desktop\firebaseui-web\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\IncrediBuild;C:\ProgramData\chocolatey\bin;C:\Program Files\Google\Google Apps Sync\;C:\Program Files\Google\Google Apps Migration\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk-14.0.1\bin;C:\Program Files\gradle-6.3\bin;C:\Users\marti\AppData\Local\Microsoft\WindowsApps;C:\Users\marti\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\marti\AppData\Local\Programs\Git\cmd;C:\Users\marti\AppData\Roaming\npm;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin
9 verbose lifecycle firebaseui@4.5.0~test: CWD: C:\Users\marti\Desktop\firebaseui-web
10 silly lifecycle firebaseui@4.5.0~test: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run build && npm run generate-test-files && ./buildtools/run_tests.sh'
10 silly lifecycle ]
11 silly lifecycle firebaseui@4.5.0~test: Returned: code: 1  signal: null
12 info lifecycle firebaseui@4.5.0~test: Failed to exec test script
13 verbose stack Error: firebaseui@4.5.0 test: `npm run build && npm run generate-test-files && ./buildtools/run_tests.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid firebaseui@4.5.0
15 verbose cwd C:\Users\marti\Desktop\firebaseui-web
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error firebaseui@4.5.0 test: `npm run build && npm run generate-test-files && ./buildtools/run_tests.sh`
22 error Exit status 1
23 error Failed at the firebaseui@4.5.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by Gregordy** [comment]
I had the same issue but you can ignore it.

Your npm install fails at the "tests" part but it doesn't matter.

If you run `npm run build` it will succeed as the crucial part of the npm install ended correctly

**Comment by dackers86** [comment]
Thank you for taking the time to submit this bug.

A new release is planned shortly, which should resolve this request. 

In the meantime, we will close this issue, if this is not resolved in the new version - please feel free to create a new issue.
