### ISSUE TITLE
Unable to sign in with email provider if Google services not present and existing account was created under Google provider

### ISSUE THREAD

**Issue by Deishelon** [firebase/firebaseui-web#847]
### [REQUIRED] Describe your environment

  * Operating System version: Android 9.0 / 11
  * Browser version: NaN
  * Firebase UI version: 7.1.1
  * Firebase SDK version: firebase-core:18.0.3 and firebase-auth:20.0.4

#### Steps to reproduce:

1) Create an account with Google as the provider on a device / emulator with Google Play services
2) Log out & try login in with email address (email provider) - this will work. 
3) Now, switch to an emulator / device without Google Play Services, and try to login using the same email.
4) You will get sign-in error.

```
2021-05-09 15:14:46.223 3876-3876/com.example.app E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Developer error
        at com.firebase.ui.auth.r.e.h$a.d(ProviderUtils.java:17)
        at com.firebase.ui.auth.r.e.h$a.a(ProviderUtils.java:1)
        at com.google.android.gms.tasks.s.run(com.google.android.gms:play-services-tasks@@17.1.0:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at e.c.b.b.b.l.a.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:1)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-05-09 15:14:46.490 3876-3876/com.example.app E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Developer error
        at com.firebase.ui.auth.ui.email.EmailActivity.Q(EmailActivity.java:2)
        at com.firebase.ui.auth.ui.email.EmailActivity.r(EmailActivity.java:1)
        at com.firebase.ui.auth.ui.email.a$a.c(CheckEmailFragment.java:3)
        at com.firebase.ui.auth.s.d.b(ResourceObserver.java:13)
        at com.firebase.ui.auth.s.d.a(ResourceObserver.java:1)
        at androidx.lifecycle.LiveData.d(LiveData.java:6)
        at androidx.lifecycle.LiveData.e(LiveData.java:8)
        at androidx.lifecycle.LiveData.o(LiveData.java:4)
        at androidx.lifecycle.d0.o(MutableLiveData.java:1)
        at com.firebase.ui.auth.s.b.k(OperableViewModel.java:1)
        at com.firebase.ui.auth.ui.email.b.p(CheckEmailHandler.java:1)
        at com.firebase.ui.auth.ui.email.b$a.a(CheckEmailHandler.java:5)
        at com.google.android.gms.tasks.w.run(com.google.android.gms:play-services-tasks@@17.1.0:3)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at e.c.b.b.b.l.a.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:1)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
#### Expected outcome:
If a user created account with Google, and then tries to sign in with email (on a device where Google Play Services are not present) - the user will be able to log-in successfully. 

#### Relevant Code:
The most basic app auth set up, the issue is on the library side, as I would expect it to carry on & log in user with email

**Comment by bojeil-google** [comment]
This repo for firebaseui-web. Please re-open your issue in the [Firebaseui-android](https://github.com/firebase/FirebaseUI-Android) repo.

**Comment by Deishelon** [comment]
Oops my bad!
