### ISSUE TITLE
`npm install` not finishing because `sass.sync is not a function`

### ISSUE THREAD

**Issue by perelin** [firebase/firebaseui-web#906]
### [REQUIRED] Describe your environment

macos 11.6
npm 7.24.0
node v16.10.0
Python 2.7.16

### [REQUIRED] Describe the problem

I´m trying to get the `/demo`to run but already `npm install` is stopping me.

#### Steps to reproduce:

Follwing the steps outlined in `/demo/README.md` `npm install` is throwing me the following error at first:

```sh
npm ERR! code 1
npm ERR! path /Users/spatinolang/code/spl/playground/firebaseui-web/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /opt/homebrew/Cellar/node/16.10.0/bin/node /Users/spatinolang/code/spl/playground/firebaseui-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
...
```

I figured it had something to do with `gulp-sass` so I updated the version to the newest `"5.0.0"`. Now node-sass is building but the following error is shown:

```sh
[16:16:59] Starting 'build-css'...
[16:16:59] 'build-css' errored after 1.06 ms
[16:16:59] TypeError: sass.sync is not a function
    at buildCss (/Users/spatinolang/code/spl/playground/firebaseui-web/gulpfile.js:351:18)
    at /Users/spatinolang/code/spl/playground/firebaseui-web/gulpfile.js:373:30
    at taskWrapper (/Users/spatinolang/code/spl/playground/firebaseui-web/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (/Users/spatinolang/code/spl/playground/firebaseui-web/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[16:16:59] 'default' errored after 1.28 min
npm ERR! code 1
npm ERR! path /Users/spatinolang/code/spl/playground/firebaseui-web
npm ERR! command failed
npm ERR! command sh -c npm run test && cp -r dist demo/public
```

#### Relevant Code:

I checked `gulpfile.js` but did see nothing suspicious. `gulp-sass` is used as described in their docs [1]

```js
const gulp = require('gulp');
const sass = require('gulp-sass');
...
const mdlSrcs = gulp.src('stylesheet/mdl.scss')
      .pipe(sass.sync().on('error', sass.logError))
      .pipe(cssInlineImages({
        webRoot: 'node_modules/material-design-lite/src',
      }));
...


```

Might be something in my environment, but I can not imagen what. Any ideas?

Thanks!

[1] https://www.npmjs.com/package/gulp-sass

**Comment by kaumbakahuma** [comment]
Thank you for your help

**Comment by jhuleatt** [comment]
gulp-sass has been updated to a version compatible with modern Node in https://github.com/firebase/firebaseui-web/releases/tag/v6.0.1
