### ISSUE TITLE
Did you forget to signal async completion?

### ISSUE THREAD

**Issue by Bohilc** [firebase/firebaseui-web#963]
### [REQUIRED] Describe your environment

  * Operating System version: macOS Monterey
  * Browser version: Version 103.0.5060.53
  * Firebase UI version: "firebaseui": "^6.0.1",
  * Firebase SDK version: "firebase": "^9.8.4",

### [REQUIRED] Describe the problem
I try copy project (from `git clone https://github.com/firebase/firebaseui-web.git`) for build UA language support. And I get error when run command `npm install`

Error is: 
```
[14%] soy_files Compiling 3 soy files to out (0.1 sec)[Closure Templates Error] Exception in thread "main" com.google.inject.internal.util.$ComputationException: java.lang.ExceptionInInitializerError
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
        at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:507)
        at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:159)
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at com.google.template.soy.MainClassUtils.createInjector(MainClassUtils.java:221)
        at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:265)
        at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)


[21:10:06] The following tasks did not complete: default, build-js, build-js-en, <parallel>, build-firebaseui-js-en, <parallel>, build-soy
[21:10:06] Did you forget to signal async completion?

```

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
git clone https://github.com/firebase/firebaseui-web.git
npm install
```

**Comment by alexregier** [comment]
Happens to me as well :(

**Comment by Blockheadtech** [comment]
Try installing Java SE Runtime Environment 8 and use this version in your terminal

**Comment by generalman025** [comment]
Try installing Java SE Runtime Environment 8 and use this version in your terminal

**Comment by KantiKuijk** [comment]
I had the same problem and this fixed it for me:
1. Set the used JRE version to major version 1.8 (JRE version 8) with: `export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
2. Run `npm install` or `npm build` succesfully

Hopefully this fixes it for others on macOS too.

**Comment by jhuleatt** [comment]
Looks like this is solved by installing a JRE.

**Comment by RyanPaulMcKenna** [comment]
installing jre did not help me, I still have the error. Any suggestions?

**Comment by KantiKuijk** [comment]
> installing jre did not help me, I still have the error. Any suggestions?

Can you confirm that the intended JRE is actually the one being used?
Installing it doesn't necessarily mean it is being used as well.
